Hw2 dictionary
danlapko/java_au_18_spring pull request #2
Opened 2018-03-29 20:22 UTC by danlapko

@dsavvinov

2018-04-17 18:00 UTC, dsavvinov requested changes
В целом впечатление положительное, код аккуратный и читается легко. Жду ответов на вопросы.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw1/TrieImpl.java
> +public class TrieImpl implements Trie {
Что-то лишнее в пулл-реквест приклеилось. Аккуратнее, пожалуйста.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +import com.sun.istack.internal.NotNull;
Это не те аннотации -- об этом можно догадаться, например, по подстроке `internal`, намекающей на то, что не нужно это использовать.

Правильно пользоваться, например, `org.jetbrains.annotations`

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +        final String key;
Minor: обычно структура класса такая:
- Поля
- Конструкторы
- Публичные методы
- Приватные методы
- Nested-классы

В камне тут, конечно, ничего не высечено, и по разумным поводам можно отсутпать от этой конвенции.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +    static private class Table extends ArrayList<Chain> {
Я понимаю благородный порыв использовать более понятные имена типов в код, но все-таки наследоваться только ради изменения имени типа не стоит. 
Помимо положительного эффекта, у такого трюка есть и отрицательный -- когда я вижу `LinkedList.get` или что-то такое, я сразу понимаю, что это за метод, какая у него реализация, асимптотика, гарантии и т.д. Когда я вижу `Chain.get`, то нужно идти и разбираться, что это за `Chain` такой и как он реализует `get`

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +    final private int initialLength = 8;
Minor: порядок ключевых слов обычно такой, что видимость на первом месте. Это такая мелочь, что я бы даже не отмечал это, если бы везде порядок был консистентный -- но это единственное место в работе, где порядок другой, и это немного режет глаз.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +        return (keyInt & 0x7FFFFFFF) % length;
Вообще, любые операции с битами почти всегда неочевидны, и их лучше сопровождать некоторым комментарием. Данное место -- не исключение.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +    DictionaryImpl(@NotNull double loadFactorLower, @NotNull double loadFactorUpper) {
Хотелось бы иметь коструктор, в котором эти параметры выбираются некоторым наиболее разумным и универсальным образом, т.к. лишь малой части потенциальных пользователей хочется разбираться, что это за "load factor'ы" такие, и как правильно выбрать значение.

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +        if ((float) keysCnt / length >= loadFactorUpper) {
Стандартный вопрос: почему именно такие условие на рехэширование, в чем его преимущества и недостатки?

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +                keysCnt--;
Почему при перекладывании entry из одной таблицы в другую как-то изменяется счетчик их количества?

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +    public @Nullable
Аннотацию `@Nullable` не обязательно ипсать ровно перед return-типом, можно и перед всеми модификаторами (так обычно и делают), т.е. вот так:
```
@Override
@Nullable
public static final int foo() { ... }
```

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +        if (key == null) {
Ой, что это за новости? Почему `null` подменяется на пустую строку, из каких соображений? Не надо ни в коем случае за пользователя ничего решать -- если он кладет `null`, то значит, он хочет положить `null`. Если не умеем работать с `null`, то нужно об этом сообщить всеми возможными способами, а не делать какую-то рандомную непредсказуемую фигню)

2018-04-17 18:00 UTC, dsavvinov commented on src/main/java/hw2/DictionaryImpl.java
> +        for (Pair pair : chain)
Code-style: скобочки отвалились

2018-04-27 00:29 UTC, merged

2018-05-26 09:47 UTC, dsavvinov commented
@danlapko Я хочу заметить, что оценка за работу пока что не стоит, и я все еще жду ответов на вопросы.

2018-05-26 09:58 UTC, dsavvinov commented
@danlapko дедлайн по исправлению замечаний: воскресенье, 27.05, 23:59.

2018-05-27 18:02 UTC, danlapko commented on src/main/java/hw2/DictionaryImpl.java
> +        if ((float) keysCnt / length >= loadFactorUpper) {
Преимущества таковы что амортизированное время работы O(n) (проходили на алгоритмах). 
Недостаток - могут быть некоторые операции добавления/удаления, которые работают O(n)ю

2018-05-27 18:11 UTC, danlapko commented on src/main/java/hw2/DictionaryImpl.java
> +                keysCnt--;
Это наверное особенности реализации, просто я не обнуляю счетчик keysCnt при создании новой таблицы.

2018-05-27 18:12 UTC, danlapko commented
Ответил на Ваши вопросы. Посмотрите, пожалуйста.

2018-05-27 18:56 UTC, dsavvinov commented
За неаккуратное обращение с `null`ами -1б, итого 9б.